config/routes.rb
CongressgameApp::Application.routes.draw do

  devise_for :users
  root "welcome#index"

  get "game", to: 'games#index'
  get "politician", to: 'politicians#index'
  resources :politicians

  # namespace :games do
  # resources :answers, :questions, :politicians

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  include Trivia::Answer
end

app/models/chosen_answer.rb
class ChosenAnswer < ActiveRecord::Base
  include Trivia::ChosenAnswer

  after_save :process_answer

  def process_answer
    if self.answer.right?
      # Add points to user, etc.
      #
      # Reward models and DSL:
      # https://github.com/SmartMedia/treasure_hunt
    end
  end
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :questions
  has_many :answers
  has_many :levels
  belongs_to :users
end

app/models/level.rb
class Level < ActiveRecord::Base
has_many :politicians
end

app/models/politician.rb
class Politician < ActiveRecord::Base  
  belongs_to :games
  has_many :questions
  has_many :answers
  has_one :levels
end
#   belongs_to :users
#   end

#   has_many :games
#   end

#   has_many :answers
#   end

#   def users
#     @users = user
#   end

#   def games
#     @game = game
#   end

#   def answers
#     @answers = answers
#   end

# end

app/models/question.rb
class Question < ActiveRecord::Base
  include Trivia::Question
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_trivia_user
  has_many :games

end

app/controllers/game_controller.rb
class GameController < ApplicationController
  
  def index
    @games = ["Challenge Your Congressman"]
  end

  def congressman
    @congressman = ["Congressman_ID"]
  end

  def congressman_challenge
    @app_challenge = [*congressman].sample
    @user_challenge = params[:congressman]. to_i
  end
  
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  
  def index
    @games = Game.all
  end

  def create
    user.create(game.new)
  end

  def question
    @questions = question
  end

  def answer
    @answers = answer
  end

  def user
    @users = user
  end

  def level
    @levels = levels
  end

  # def show
  #   @politicians = Politician params[id]
  #   @games = Game.new
  # end
end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_filter :authenticate_user!

  def index
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/politicians_helper.rb
module PoliticiansHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>CongressGameApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>

<body>
<div class="container">
  <header class="row">
    <nav class="navbar navbar-pills">
      <div class="navbar-header">
        <%= link_to(image_tag('Congress.png', class: 'logo'), root_path) %>
        <%= link_to "Home", root_path, class: 'navbar-brand' %>
      </div>
      <ul class="nav navbar-nav">
        <li><%= link_to "Play Now", game_path %></li>
        <li><%= link_to "Congressional Challengers", politicians_path %></li>
        <li><%= link_to "Sign-Up", new_user_registration_path %></li>
        <li><%= link_to "Log In", new_user_session_path %></li>
        <li><%= link_to "Log Out", destroy_user_session_path, method: :delete%></li>
      </ul>
    </nav>
  </header>


  <%= yield %>

</div>
</body>
</html>

app/views/politicans/index.html.erb
<h1>Politicans</h1>
<p>Meet your opponents</p>